require 'model/time-set.rb'
require 'model/animal'
require 'model/authorizer'
require 'model/group'
require 'model/procedure'
require 'model/reservation'
require 'model/use'
require 'model/procedure-description'
require 'model/timeslice'
require 'model/rules'
require 'model/query-maker'
require 'model/tuple-cache'
require 'model/tuple-publisher'
require 'model/availability'

