require './strangled-src/view/href'
require './strangled-src/view/animal-list-view'
require './strangled-src/view/reservation-view'
require './strangled-src/view/procedure-partial'
require './strangled-src/view/animals-with-pending-reservations-view'
require './strangled-src/view/reservation-dates-cell'
require './strangled-src/view/uses-of-many-animals-view'
require './strangled-src/view/timeslice-usage-text'
