require 'view/animal-list-view'
require 'view/reservation-list-view'
require 'view/reservation-view'
require 'view/procedure-partial'
require 'view/animals-with-pending-reservations-view'
require 'view/reservation-dates-cell'
